// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfCNxybNRDncy1op3ROIPhdwVfkD4-Hvg',
    appId: '1:932995165005:web:0d7b733c478c9a1ca1e504',
    messagingSenderId: '932995165005',
    projectId: 'hackathon-in-nagonova',
    authDomain: 'hackathon-in-nagonova.firebaseapp.com',
    storageBucket: 'hackathon-in-nagonova.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ4g4tmKnnSm97X3c266_CWk1pG-rDzbo',
    appId: '1:932995165005:android:e3049c3381ef2e2aa1e504',
    messagingSenderId: '932995165005',
    projectId: 'hackathon-in-nagonova',
    storageBucket: 'hackathon-in-nagonova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtpPkspzB3T7A-4nAbH7DS7MNkGcOG8w',
    appId: '1:932995165005:ios:33938718b72d38e7a1e504',
    messagingSenderId: '932995165005',
    projectId: 'hackathon-in-nagonova',
    storageBucket: 'hackathon-in-nagonova.firebasestorage.app',
    iosBundleId: 'com.fenc0268.nagonovaHackathon.hackathonApp',
  );
}
